# Generated by Django 4.2.9 on 2024-03-03 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Promedios', '0003_estudiante_fecha_nacimiento_estudiante_sexo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promedio',
            name='notas',
            field=models.ManyToManyField(to='Promedios.nota'),
        ),
    ]
