# Generated by Django 4.2.9 on 2024-03-03 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Promedios', '0004_promedio_notas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promedio',
            name='notas',
        ),
    ]
