# Generated by Django 4.2.9 on 2024-03-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Promedios', '0005_remove_promedio_notas'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='grado',
            field=models.CharField(blank=True, choices=[('1ro_de_primaria', 'Primero de Primaria'), ('2do_de_primaria', 'Segundo de Primaria'), ('3ro_de_primaria', 'Tercero de Primaria'), ('4to_de_primaria', 'Cuarto de Primaria'), ('5to_de_primaria', 'Quinto de Primaria'), ('6to_de_primaria', 'Sexto de Primaria'), ('1ro_de_secundaria', 'Primero de Secundaria'), ('2do_de_secundaria', 'Segundo de Secundaria'), ('3ro_de_secundaria', 'Tercero de Secundaria'), ('4to_de_secundaria', 'Cuarto de Secundaria'), ('5to_de_secundaria', 'Quinto de Secundaria')], max_length=20),
        ),
    ]
