# Generated by Django 4.2.9 on 2024-03-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Promedios', '0006_estudiante_grado'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='seccion',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1),
        ),
    ]
