# Generated by Django 4.2.9 on 2024-03-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Promedios', '0007_estudiante_seccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='grado',
            field=models.CharField(blank=True, choices=[('1ro de primaria', 'Primero de Primaria'), ('2do de primaria', 'Segundo de Primaria'), ('3ro de primaria', 'Tercero de Primaria'), ('4to de primaria', 'Cuarto de Primaria'), ('5to de primaria', 'Quinto de Primaria'), ('6to de primaria', 'Sexto de Primaria'), ('1ro de secundaria', 'Primero de Secundaria'), ('2do de secundaria', 'Segundo de Secundaria'), ('3ro de secundaria', 'Tercero de Secundaria'), ('4to de secundaria', 'Cuarto de Secundaria'), ('5to de secundaria', 'Quinto de Secundaria')], max_length=20),
        ),
    ]
