# Generated by Django 4.2.9 on 2024-04-12 17:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Promedios', '0008_alter_estudiante_grado'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
