# Generated by Django 4.2.9 on 2024-11-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Promedios', '0009_curso_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
